import { Link, useLocation, useParams } from "wouter";
import { ArrowLeft, BriefcaseBusiness, CalendarDays, Check, ChevronRight, Clock3, DollarSign, ExternalLink, MessageCircle, ShieldCheck, Star, WalletCards } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { ApplicationShell, EmptyState, PageHeader, StatusBadge } from "@/components/shell/ZyloShell";
import { Button } from "@/components/ui/button";
import { formatJobBudget } from "@shared/currency";
import { APPLICATION_STAGE_LABELS, APPLICATION_STAGE_ORDER, applicationStageMessage } from "@shared/applicationLifecycle";
import { VOCATION_LABELS, type VocationKey } from "@shared/vocations";
import { toast } from "sonner";

function formatDate(value: Date | string | null | undefined) {
  return value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Not specified";
}

const tone: Record<string, "success" | "info" | "warning" | "error" | "neutral"> = { submitted: "info", under_review: "warning", shortlisted: "warning", interview: "info", accepted: "success", active: "success", completed: "success", rejected: "error", withdrawn: "neutral" };

export default function ApplicationDetail() {
  const { id } = useParams<{ id: string }>();
  const [, navigate] = useLocation();
  const applicationQuery = trpc.applications.detail.useQuery({ id: Number(id) }, { enabled: Number(id) > 0 });
  const application = applicationQuery.data;
  const message = trpc.messaging.getOrCreateConversation.useMutation({ onSuccess: (conversation) => navigate(`/messages/${conversation.id}`), onError: () => toast.error("We couldn't open the employer conversation.") });
  if (applicationQuery.isLoading) return <ApplicationShell role="professional"><div className="grid gap-4"><div className="h-10 w-48 animate-pulse rounded-lg bg-muted" /><div className="h-96 animate-pulse rounded-2xl border border-border bg-card" /></div></ApplicationShell>;
  if (applicationQuery.isError || !application) return <ApplicationShell role="professional"><EmptyState title="Application not found" description="This application may not exist or is not available to your account." action={<Link href="/applications"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4" />Back to applications</Button></Link>} /></ApplicationShell>;
  const stage = application.stage;
  const currentIndex = APPLICATION_STAGE_ORDER.indexOf(stage);
  const payment = application.escrow?.status === "funded" ? { label: "Escrow funded", detail: "Funds are secured in the existing escrow flow.", tone: "success" as const } : application.escrow?.status === "released" ? { label: "Payment released", detail: "The escrow payment has been released.", tone: "success" as const } : application.escrow?.status === "pending" ? { label: "Awaiting escrow", detail: "Escrow has not yet been funded.", tone: "warning" as const } : null;
  const canMessage = ["shortlisted", "interview", "accepted", "active"].includes(stage) && Boolean(application.employerId ?? application.job.clientId);
  return <ApplicationShell role="professional"><div className="space-y-6"><div className="flex flex-wrap items-center gap-3"><Link href="/applications" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to applications</Link></div><PageHeader title={application.job.title} description={`${application.employerName} · ${application.job.location}`} action={<Link href={`/jobs/${application.job.id}?from=${encodeURIComponent("/applications")}`}><Button variant="outline"><ExternalLink className="mr-2 h-4 w-4" />View job</Button></Link>} />
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><main className="space-y-5"><section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={tone[stage]} label={APPLICATION_STAGE_LABELS[stage]} /><span className="text-xs text-muted-foreground">Application #{application.id}</span>{application.employerVerified && <span className="inline-flex items-center gap-1 text-xs text-emerald-300"><ShieldCheck className="h-3.5 w-3.5" />Verified employer</span>}</div><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{applicationStageMessage(stage)}</p><div className="mt-6 overflow-x-auto pb-1"><div className="flex min-w-[620px] items-center gap-2">{APPLICATION_STAGE_ORDER.map((step, index) => <div key={step} className="flex flex-1 items-center gap-2"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border text-xs font-semibold ${index <= currentIndex ? "border-primary/50 bg-primary/15 text-primary" : "border-border bg-muted/20 text-muted-foreground"}`}>{index < currentIndex ? <Check className="h-4 w-4" /> : index + 1}</div><span className={`text-xs ${index === currentIndex ? "font-semibold text-foreground" : "text-muted-foreground"}`}>{APPLICATION_STAGE_LABELS[step]}</span>{index < APPLICATION_STAGE_ORDER.length - 1 && <span className={`h-px flex-1 ${index < currentIndex ? "bg-primary/50" : "bg-border"}`} />}</div>)}</div></div></section>
      <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3"><BriefcaseBusiness className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold">Job information</h2></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{application.job.description}</p><div className="mt-5 grid gap-4 border-t border-border pt-5 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Vocation</p><p className="mt-1 font-medium">{VOCATION_LABELS[application.job.vocation as VocationKey] ?? application.job.vocation}</p></div><div><p className="text-xs text-muted-foreground">Budget</p><p className="mt-1 font-medium">{formatJobBudget(application.job.budget, application.job.currency)}</p></div><div><p className="text-xs text-muted-foreground">Deadline</p><p className="mt-1 font-medium">{formatDate(application.job.deadline)}</p></div></div></section>
      <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3"><DollarSign className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold">Your submission</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Submitted</p><p className="mt-1 inline-flex items-center gap-1.5 font-medium"><CalendarDays className="h-4 w-4 text-muted-foreground" />{formatDate(application.createdAt)}</p></div><div><p className="text-xs text-muted-foreground">Your bid</p><p className="mt-1 font-semibold">{formatJobBudget(application.bidAmount, application.job.currency)}</p></div><div><p className="text-xs text-muted-foreground">Last updated</p><p className="mt-1 inline-flex items-center gap-1.5 font-medium"><Clock3 className="h-4 w-4 text-muted-foreground" />{formatDate(application.updatedAt)}</p></div></div><div className="mt-5 rounded-xl border border-border bg-muted/20 p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Cover note</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{application.coverLetter}</p></div></section>
      <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold">Application timeline</h2></div><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-500/15 text-emerald-300"><Check className="h-3.5 w-3.5" /></span><div><p className="text-sm font-medium">Application submitted</p><p className="text-xs text-muted-foreground">{formatDate(application.createdAt)}</p></div></div><div className="flex gap-3"><span className={`mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${currentIndex > 0 ? "bg-emerald-500/15 text-emerald-300" : "bg-primary/15 text-primary"}`}>{currentIndex > 0 ? <Check className="h-3.5 w-3.5" /> : <ChevronRight className="h-3.5 w-3.5" />}</span><div><p className="text-sm font-medium">Current stage: {APPLICATION_STAGE_LABELS[stage]}</p><p className="text-xs text-muted-foreground">Derived from the authoritative application and hiring workflow records.</p></div></div></div></section>
    </main><aside className="space-y-4 lg:sticky lg:top-24"><section className="rounded-2xl border border-border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Application summary</p><p className="mt-3 text-xl font-semibold">{APPLICATION_STAGE_LABELS[stage]}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{applicationStageMessage(stage)}</p><div className="mt-5 space-y-2"><Link href={`/jobs/${application.job.id}?from=${encodeURIComponent(`/applications/${application.id}`)}`}><Button variant="outline" className="w-full">View job</Button></Link>{canMessage && application.employerId && <Button className="w-full" disabled={message.isPending} onClick={() => message.mutate({ jobId: application.job.id, otherUserId: application.employerId! })}><MessageCircle className="mr-2 h-4 w-4" />Message employer</Button>}{isAcceptedStage(stage) && <Link href="/payments"><Button variant="outline" className="w-full"><WalletCards className="mr-2 h-4 w-4" />View payments</Button></Link>}{stage === "completed" && <Link href={`/jobs/${application.job.id}?from=${encodeURIComponent(`/applications/${application.id}`)}&review=1`}><Button variant="outline" className="w-full"><Star className="mr-2 h-4 w-4" />Leave review</Button></Link>}</div></section>{payment && <section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-primary" /><h2 className="font-semibold">Payment</h2></div><StatusBadge status={payment.tone} label={payment.label} /><p className="mt-3 text-sm leading-6 text-muted-foreground">{payment.detail}</p><Link href="/payments" className="mt-4 inline-flex items-center text-sm font-medium text-primary hover:underline">Open payments <ChevronRight className="ml-1 h-4 w-4" /></Link></section>}</aside></div></div></ApplicationShell>;
}

function isAcceptedStage(stage: string) { return ["accepted", "active", "completed"].includes(stage); }
