import { Link, useParams } from "wouter";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, ExternalLink, FileBadge2, Loader2, MapPin, MessageSquare, ShieldCheck, Star, UserRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { ApplicationShell, EmptyState, PageHeader, StatusBadge } from "@/components/shell/ZyloShell";
import { Button } from "@/components/ui/button";
import { VOCATION_LABELS, type VocationKey } from "@shared/vocations";
import { parseProfileMetadata } from "@shared/profile";

function formatDate(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleDateString(undefined, { month: "short", year: "numeric" }) : "Present"; }
function parseSkills(value: string | null | undefined) { return (value ?? "").split(",").map((skill) => skill.trim()).filter(Boolean); }

export default function ProfessionalProfilePage() {
  const { id } = useParams<{ id: string }>();
  const query = trpc.talent.getProfile.useQuery({ userId: Number(id) }, { enabled: Number(id) > 0 });
  if (query.isLoading) return <ApplicationShell><div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div></ApplicationShell>;
  if (query.isError || !query.data) return <ApplicationShell><EmptyState icon={UserRound} title="Professional profile unavailable" description="This profile may be private or no longer active." action={<Link href="/talent"><Button variant="outline"><ArrowLeft className="h-4 w-4 mr-2" />Back to talent</Button></Link>} /></ApplicationShell>;

  const { profile, user: person, portfolio, qualifications, experience, verifications, reviews, completedJobs } = query.data;
  const metadata = parseProfileMetadata(profile.profileMetadata);
  const skills = parseSkills(profile.skills);
  return <ApplicationShell>
    <div className="mb-5"><Link href="/talent" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to talent directory</Link></div>
    <PageHeader title={person.name || "Professional profile"} description={`${metadata.headline || (VOCATION_LABELS[profile.vocation as VocationKey] ?? profile.vocation)} · ${profile.location || "Location not listed"}`} action={<div className="flex gap-2"><Link href="/messages"><Button><MessageSquare className="h-4 w-4 mr-2" />Start a conversation</Button></Link></div>} />
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px] items-start">
      <main className="space-y-6 min-w-0">
        <section className="rounded-2xl border border-border bg-card p-6 md:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-3xl bg-primary/10 text-2xl font-bold text-primary">{person.avatarUrl ? <img src={person.avatarUrl} alt="" className="h-full w-full rounded-3xl object-cover" /> : (person.name?.slice(0, 1).toUpperCase() || "P")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold">{person.name || "Professional"}</h2>{person.isVerified && <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-500"><CheckCircle2 className="h-4 w-4" />Verified account</span>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{profile.bio || "This professional has not added a public biography yet."}</p><div className="mt-4 flex flex-wrap gap-2">{metadata.additionalVocations?.map((vocation) => <StatusBadge key={vocation} status="neutral" label={vocation} />)}{metadata.specializations?.slice(0, 5).map((specialization) => <StatusBadge key={specialization} status="info" label={specialization} />)}{(metadata.availabilityStatus === "available_now" || (metadata.availabilityStatus === undefined && profile.isAvailable)) && <StatusBadge status="success" label="Available for work" />}{metadata.availabilityStatus === "currently_working" && <StatusBadge status="warning" label="Currently engaged" />}{metadata.availabilityStatus === "emergency_only" && <StatusBadge status="info" label="Emergency jobs only" />}{profile.yearsExperience !== null && <StatusBadge status="neutral" label={`${profile.yearsExperience} years experience`} />}{profile.hourlyRate && metadata.rateVisibility !== "private" && <StatusBadge status="info" label={`₦${Number(profile.hourlyRate).toLocaleString()} / hour`} />}{reviews.length > 0 && <StatusBadge status="neutral" label={`${reviews.length} review${reviews.length === 1 ? "" : "s"}`} />}</div></div></div>{skills.length > 0 && <div className="mt-6 flex flex-wrap gap-2 border-t border-border pt-5">{skills.map((skill) => <span key={skill} className="rounded-full border border-border bg-background px-3 py-1.5 text-xs font-medium">{skill}</span>)}</div>}</section>
        <section className="rounded-2xl border border-border bg-card p-6 md:p-8"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Where and how I work</h2><p className="mt-1 text-sm text-muted-foreground">Service area and working preferences shared by this professional.</p></div><MapPin className="h-5 w-5 text-primary" /></div><div className="mt-6 grid gap-5 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Service area</p><p className="mt-2 text-sm">{profile.location || "Location not listed"}</p>{metadata.serviceAreas?.length ? <div className="mt-3 flex flex-wrap gap-2">{metadata.serviceAreas.map((area) => <span key={area} className="rounded-full border border-border bg-background px-3 py-1.5 text-xs">{area}</span>)}</div> : null}<p className="mt-3 text-xs text-muted-foreground">{metadata.serviceRadiusKm !== undefined ? `Preferred service radius: ${metadata.serviceRadiusKm} km. ` : ""}{metadata.willingToTravel ? "Willing to travel beyond listed areas." : "Travel preference not listed."}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Work preferences</p><p className="mt-2 text-sm">{metadata.employmentTypes?.map((item) => item.replace("_", " ")).join(", ") || "Not listed"}</p><p className="mt-2 text-xs text-muted-foreground">{metadata.preferredProjectTypes?.join(", ") || "Project preferences not listed."}</p>{metadata.languages?.length ? <p className="mt-3 text-xs text-muted-foreground">Languages: {metadata.languages.map((item) => `${item.language} · ${item.proficiency}`).join(", ")}</p> : null}</div></div>{metadata.equipment?.length || metadata.transportation ? <p className="mt-5 border-t border-border pt-4 text-xs text-muted-foreground">Capabilities: {[...(metadata.equipment ?? []), metadata.transportation].filter(Boolean).join(", ")}</p> : null}</section>
        <section className="rounded-2xl border border-border bg-card p-6 md:p-8"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Portfolio</h2><p className="mt-1 text-sm text-muted-foreground">Selected work shared publicly by this professional.</p></div><BriefcaseBusiness className="h-5 w-5 text-primary" /></div>{portfolio.length ? <div className="mt-6 grid gap-4 md:grid-cols-2">{portfolio.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-border bg-background/60">{item.imageUrl && <img src={item.imageUrl} alt="" className="h-40 w-full object-cover" /> }<div className="p-4"><h3 className="font-semibold">{item.title}</h3>{item.description && <p className="mt-2 line-clamp-3 text-sm leading-6 text-muted-foreground">{item.description}</p>}{item.skills && <p className="mt-3 text-xs text-muted-foreground">{item.skills}</p>}{item.projectUrl && <a href={item.projectUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">View project <ExternalLink className="h-3.5 w-3.5" /></a>}</div></article>)}</div> : <p className="mt-6 text-sm text-muted-foreground">No public portfolio items yet.</p>}</section>
        <section className="grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><FileBadge2 className="h-4 w-4 text-primary" />Qualifications</h2>{qualifications.length ? <div className="mt-5 space-y-4">{qualifications.map((item) => <div key={item.id} className="border-l-2 border-primary/30 pl-4"><p className="font-medium">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.issuingOrg}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(item.issueDate)}{item.expiryDate ? ` – ${formatDate(item.expiryDate)}` : ""}</p></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No qualifications added yet.</p>}</div><div className="rounded-2xl border border-border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><BriefcaseBusiness className="h-4 w-4 text-primary" />Work history</h2>{experience.length ? <div className="mt-5 space-y-4">{experience.map((item) => <div key={item.id} className="border-l-2 border-primary/30 pl-4"><p className="font-medium">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.companyName}{item.location ? ` · ${item.location}` : ""}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(item.startDate)} – {item.isCurrent ? "Present" : formatDate(item.endDate)}</p></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No work history added yet.</p>}</div></section>
        <section className="rounded-2xl border border-border bg-card p-6 md:p-8"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Reputation</h2><p className="mt-1 text-sm text-muted-foreground">Reviews from completed work on Zylobridge.</p></div><div className="text-right">{reviews.length > 0 ? <><div className="flex items-center gap-1 font-semibold"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />{Number(profile.averageRating ?? 0).toFixed(1)}</div><p className="text-xs text-muted-foreground">{reviews.length} public reviews</p></> : <><p className="font-semibold">New professional</p><p className="text-xs text-muted-foreground">No public reviews yet</p></>}</div></div>{reviews.length ? <div className="mt-6 space-y-4">{reviews.map((review, index) => <blockquote key={`${review.createdAt}-${index}`} className="rounded-xl border border-border bg-background/60 p-4"><div className="flex items-center gap-1 text-amber-500">{Array.from({ length: 5 }).map((_, star) => <Star key={star} className={`h-3.5 w-3.5 ${star < review.rating ? "fill-current" : ""}`} />)}</div>{review.comment && <p className="mt-3 text-sm leading-6 text-muted-foreground">“{review.comment}”</p>}<footer className="mt-3 text-xs text-muted-foreground">{formatDate(review.createdAt)}</footer></blockquote>)}</div> : <p className="mt-6 text-sm text-muted-foreground">No reviews have been published yet.</p>}</section>
      </main>
      <aside className="space-y-4 lg:sticky lg:top-24"><section className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">Trust overview</h2><div className="mt-5 space-y-4 text-sm"><p className="flex items-center justify-between"><span className="text-muted-foreground">Completed jobs</span><span className="font-semibold">{completedJobs}</span></p><p className="flex items-center justify-between"><span className="text-muted-foreground">Rating</span><span className="font-semibold">{reviews.length > 0 ? `${Number(profile.averageRating ?? 0).toFixed(1)} / 5` : "Not yet rated"}</span></p><p className="flex items-center justify-between"><span className="text-muted-foreground">Location</span><span className="max-w-[140px] text-right font-semibold">{profile.location || "Not listed"}</span></p></div></section><section className="rounded-2xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-emerald-500" />Verification</h2><div className="mt-4 space-y-3">{verifications.length ? verifications.map((verification) => <div key={verification.verificationType} className="flex items-center justify-between gap-3 text-sm"><span className="capitalize text-muted-foreground">{verification.verificationType.replaceAll("_", " ")}</span><StatusBadge status={verification.status === "verified" ? "success" : verification.status === "rejected" ? "error" : "warning"} label={verification.status.replaceAll("_", " ")} /></div>) : <p className="text-sm text-muted-foreground">No verification records are public yet.</p>}</div></section></aside>
    </div>
  </ApplicationShell>;
}
