import { useAuth } from "@/_core/hooks/useAuth";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ShopProductCard } from "@/components/shop/ShopProductCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BriefcaseBusiness, FileText, Heart, Loader2, Package, RotateCcw, ShieldCheck, ShoppingBag, Store, Truck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

const NAV = [
  { href: "/shop/account", label: "Overview", icon: ShoppingBag },
  { href: "/shop/wishlist", label: "Saved products", icon: Heart },
  { href: "/shop/requests", label: "Requests", icon: RotateCcw },
  { href: "/shop/procurement", label: "Procurement", icon: BriefcaseBusiness },
  { href: "/shop/digital", label: "Digital access", icon: FileText },
  { href: "/shop/orders", label: "Orders", icon: Truck },
  { href: "/shop/seller", label: "Seller center", icon: Store },
];

export default function ShopWorkspace() {
  const { isAuthenticated, loading: authLoading } = useAuth();
  const [location] = useLocation();
  const section = location.split("?")[0].split("/").pop() || "account";
  const utils = trpc.useUtils();
  const saved = trpc.shopExtensions.saved.list.useQuery(undefined, { enabled: isAuthenticated });
  const requests = trpc.shopExtensions.requests.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const procurement = trpc.shopExtensions.procurement.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const access = trpc.shopExtensions.access.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const seller = trpc.shopExtensions.seller.me.useQuery(undefined, { enabled: isAuthenticated });
  const products = trpc.commerce.products.list.useQuery({ first: 100 }, { enabled: isAuthenticated && section === "wishlist", retry: 1 });
  const [businessName, setBusinessName] = useState("");
  const [sellerType, setSellerType] = useState("supplier");
  const [country, setCountry] = useState("ZA");
  const [sellerDescription, setSellerDescription] = useState("");
  const [rfqTitle, setRfqTitle] = useState("");
  const [rfqDescription, setRfqDescription] = useState("");
  const [deliveryLocation, setDeliveryLocation] = useState("");
  const [itemTitle, setItemTitle] = useState("");
  const [itemQuantity, setItemQuantity] = useState(1);
  const sellerMutation = trpc.shopExtensions.seller.submitApplication.useMutation({ onSuccess: () => { toast.success("Seller application submitted"); utils.shopExtensions.seller.me.invalidate(); } });
  const rfqMutation = trpc.shopExtensions.procurement.create.useMutation({ onSuccess: () => { toast.success("Procurement request published"); setRfqTitle(""); setRfqDescription(""); setDeliveryLocation(""); setItemTitle(""); utils.shopExtensions.procurement.listMine.invalidate(); } });
  const savedProducts = useMemo(() => products.data?.filter((product) => saved.data?.some((item) => item.shopifyProductId === product.id)) ?? [], [products.data, saved.data]);

  if (authLoading) return <div className="grid min-h-screen place-items-center bg-[#080d14]"><Loader2 className="h-8 w-8 animate-spin text-violet-400" /></div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#080d14] text-white"><Navbar /><main className="mx-auto max-w-2xl px-4 py-24 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-violet-300" /><h1 className="mt-4 text-3xl font-black">Sign in to your Shop workspace</h1><p className="mt-3 text-slate-400">Saved products, requests, procurement, seller applications, and digital grants are private account data.</p><Button asChild className="mt-6"><Link href={`/sign-in?next=${encodeURIComponent(location)}`}>Sign in securely</Link></Button></main></div>;

  const renderSection = () => {
    if (section === "wishlist") return <section><h1 className="text-3xl font-black">Saved products</h1><p className="mt-2 text-slate-400">Your private shortlist of live Shopify listings.</p>{products.isLoading ? <Loader2 className="mt-10 h-7 w-7 animate-spin text-violet-400" /> : savedProducts.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{savedProducts.map((product) => <ShopProductCard key={product.id} product={product} />)}</div> : <Empty icon={Heart} title="No saved products" text="Use the heart control on a product card to build this list." href="/shop" action="Browse products" />}</section>;
    if (section === "requests") return <section><h1 className="text-3xl font-black">Rental, service, training & digital requests</h1><p className="mt-2 text-slate-400">Requests are reviewed before any separate payment or access decision.</p>{requests.data?.length ? <div className="mt-7 space-y-3">{requests.data.map((request) => <div key={request.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold capitalize">{request.requestType} request</p><p className="mt-1 text-sm text-slate-500">{request.productHandle} · Quantity {request.quantity}</p></div><span className="rounded-full bg-violet-500/12 px-3 py-1 text-xs font-bold capitalize text-violet-200">{request.status.replaceAll("_", " ")}</span></div></div>)}</div> : <Empty icon={RotateCcw} title="No Shop requests" text="Rental, service, training, and digital requests will appear here." href="/shop" action="Explore the catalog" />}</section>;
    if (section === "procurement") return <section><h1 className="text-3xl font-black">Procurement & RFQs</h1><p className="mt-2 text-slate-400">Publish a structured sourcing request for approved sellers without exposing private buyer data.</p><div className="mt-7 grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={(event) => { event.preventDefault(); rfqMutation.mutate({ title: rfqTitle, description: rfqDescription, deliveryLocation, currency: "ZAR", items: [{ title: itemTitle, quantity: itemQuantity }] }); }} className="space-y-4 rounded-3xl border border-white/10 bg-[#101824] p-6"><h2 className="text-xl font-bold">Create a request</h2><Input required minLength={4} value={rfqTitle} onChange={(event) => setRfqTitle(event.target.value)} placeholder="Request title" className="border-white/10 bg-white/[0.03]" /><Textarea required minLength={20} value={rfqDescription} onChange={(event) => setRfqDescription(event.target.value)} placeholder="Scope, standards, delivery requirements, and evaluation criteria" className="min-h-28 border-white/10 bg-white/[0.03]" /><Input required value={deliveryLocation} onChange={(event) => setDeliveryLocation(event.target.value)} placeholder="Delivery location" className="border-white/10 bg-white/[0.03]" /><Input required value={itemTitle} onChange={(event) => setItemTitle(event.target.value)} placeholder="Item or service required" className="border-white/10 bg-white/[0.03]" /><Input required type="number" min={1} value={itemQuantity} onChange={(event) => setItemQuantity(Math.max(1, Number(event.target.value)))} className="border-white/10 bg-white/[0.03]" /><Button className="w-full" disabled={rfqMutation.isPending}>{rfqMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Publish RFQ</Button></form><div><h2 className="text-xl font-bold">Your requests</h2>{procurement.data?.length ? <div className="mt-4 space-y-3">{procurement.data.map((request) => <div key={request.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><p className="font-bold">{request.title}</p><p className="mt-2 line-clamp-2 text-sm text-slate-500">{request.description}</p><div className="mt-3 flex items-center justify-between text-xs"><span className="text-slate-500">{request.deliveryLocation}</span><span className="rounded-full bg-teal-500/10 px-2.5 py-1 font-bold capitalize text-teal-200">{request.status}</span></div></div>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-8 text-sm text-slate-500">No procurement requests yet.</p>}</div></div></section>;
    if (section === "seller") return <section><h1 className="text-3xl font-black">Seller center</h1><p className="mt-2 text-slate-400">Apply for verification before products, rentals, services, training, or digital resources can be represented on the marketplace.</p>{seller.data ? <div className="mt-7 rounded-3xl border border-white/10 bg-[#101824] p-7"><Store className="h-8 w-8 text-violet-300" /><h2 className="mt-4 text-xl font-bold">{seller.data.businessName}</h2><p className="mt-2 text-sm text-slate-400">Seller type: {seller.data.sellerType.replaceAll("_", " ")}</p><span className="mt-5 inline-flex rounded-full bg-violet-500/12 px-3 py-1 text-sm font-bold capitalize text-violet-200">{seller.data.status.replaceAll("_", " ")}</span><p className="mt-4 text-sm leading-6 text-slate-500">Products are managed in Shopify. Approval does not create inventory, certifications, or ratings.</p></div> : <form onSubmit={(event) => { event.preventDefault(); sellerMutation.mutate({ businessName, sellerType: sellerType as "supplier" | "rental_provider" | "trainer" | "service_provider" | "digital_publisher", country: country as "NG" | "ZA", description: sellerDescription }); }} className="mt-7 max-w-2xl space-y-4 rounded-3xl border border-white/10 bg-[#101824] p-7"><Input required minLength={2} value={businessName} onChange={(event) => setBusinessName(event.target.value)} placeholder="Registered business or provider name" className="border-white/10 bg-white/[0.03]" /><select value={sellerType} onChange={(event) => setSellerType(event.target.value)} className="h-11 w-full rounded-xl border border-white/10 bg-[#111824] px-3 text-white"><option value="supplier">Supplier</option><option value="rental_provider">Rental provider</option><option value="trainer">Trainer</option><option value="service_provider">Service provider</option><option value="digital_publisher">Digital publisher</option></select><select value={country} onChange={(event) => setCountry(event.target.value)} className="h-11 w-full rounded-xl border border-white/10 bg-[#111824] px-3 text-white"><option value="ZA">South Africa</option><option value="NG">Nigeria</option></select><Textarea required minLength={40} value={sellerDescription} onChange={(event) => setSellerDescription(event.target.value)} placeholder="Describe your company, fulfillment capabilities, service coverage, and the categories you intend to supply." className="min-h-32 border-white/10 bg-white/[0.03]" /><div className="rounded-xl bg-amber-500/10 p-3 text-xs leading-5 text-amber-100">Do not claim unverified certifications, ratings, inventory, or authorization for restricted products.</div><Button disabled={sellerMutation.isPending}>{sellerMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Submit application</Button></form>}</section>;
    if (section === "digital") return <section><h1 className="text-3xl font-black">Digital access</h1><p className="mt-2 text-slate-400">Access appears only after an authorized server-side grant. Checkout success alone never exposes a protected resource.</p>{access.data?.length ? <div className="mt-7 space-y-3">{access.data.map((grant) => <div key={grant.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><p className="font-bold">{grant.productHandle}</p><p className="mt-1 text-sm text-slate-500">{grant.grantType} access</p>{grant.resourceUrl && <Button asChild className="mt-4"><a href={grant.resourceUrl} rel="noreferrer">Open resource</a></Button>}</div>)}</div> : <Empty icon={FileText} title="No digital access grants" text="Verified access grants will appear here after the responsible commerce workflow confirms eligibility." href="/shop?modality=digital" action="Browse digital resources" />}</section>;
    if (section === "orders") return <section><h1 className="text-3xl font-black">Shop orders</h1><p className="mt-2 text-slate-400">Shopify hosted checkout is the authoritative system for payment confirmation, order creation, tax, shipping, and fulfillment updates.</p><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-[#101824] p-7"><Truck className="h-8 w-8 text-teal-300" /><h2 className="mt-4 text-xl font-bold">Hosted order confirmation</h2><p className="mt-2 text-sm leading-6 text-slate-500">After checkout, use the Shopify confirmation page and merchant email for the current order record. ZYLOBRIDGE does not fabricate a parallel Shopify order history.</p></div><div className="rounded-3xl border border-white/10 bg-[#101824] p-7"><Package className="h-8 w-8 text-violet-300" /><h2 className="mt-4 text-xl font-bold">Legacy marketplace orders</h2><p className="mt-2 text-sm leading-6 text-slate-500">Orders created by the earlier ZYLOBRIDGE Paystack shop remain available separately for continuity.</p><Button asChild variant="outline" className="mt-5"><Link href="/orders">View legacy orders <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>;
    return <section><h1 className="text-3xl font-black">Shop account</h1><p className="mt-2 text-slate-400">Your private sourcing, request, access, and supplier workspace.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ value: saved.data?.length ?? 0, label: "saved products", href: "/shop/wishlist" }, { value: requests.data?.length ?? 0, label: "active requests", href: "/shop/requests" }, { value: procurement.data?.length ?? 0, label: "procurement requests", href: "/shop/procurement" }, { value: access.data?.length ?? 0, label: "access grants", href: "/shop/digital" }].map((metric) => <Link key={metric.label} href={metric.href} className="rounded-3xl border border-white/10 bg-[#101824] p-6 transition hover:border-violet-400/40"><p className="text-3xl font-black">{metric.value}</p><p className="mt-2 text-sm text-slate-500">{metric.label}</p></Link>)}</div><div className="mt-8 rounded-3xl border border-violet-400/20 bg-violet-500/10 p-7"><ShieldCheck className="h-8 w-8 text-violet-300" /><h2 className="mt-4 text-xl font-bold">Clear commerce boundaries</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-300">Shopify remains authoritative for catalog, inventory, price, cart, checkout, payment, orders, and fulfillment. This workspace stores only the authenticated ZYLOBRIDGE workflows that Shopify does not model.</p></div></section>;
  };

  return <div className="min-h-screen bg-[#080d14] text-white"><Navbar /><main className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[240px_1fr]"><aside><Link href="/shop" className="mb-6 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white">← Back to Shop</Link><nav className="flex gap-2 overflow-x-auto pb-2 lg:flex-col">{NAV.map((item) => <Link key={item.href} href={item.href} className={`flex shrink-0 items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition ${location.split("?")[0] === item.href ? "bg-violet-500/15 text-violet-200" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><item.icon className="h-4 w-4" />{item.label}</Link>)}</nav></aside><div className="min-w-0">{renderSection()}</div></main><Footer /></div>;
}

function Empty({ icon: Icon, title, text, href, action }: { icon: typeof Package; title: string; text: string; href: string; action: string }) {
  return <div className="mt-7 rounded-3xl border border-dashed border-white/10 p-14 text-center"><Icon className="mx-auto h-9 w-9 text-slate-700" /><h2 className="mt-4 text-xl font-bold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p><Button asChild className="mt-5"><Link href={href}>{action}</Link></Button></div>;
}
